// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaDeCompras.DAL;

#nullable disable

namespace SistemaDeCompras.Migrations
{
    [DbContext(typeof(SistemaDeComprasDbContext))]
    partial class SistemaDeComprasDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("SistemaDeCompras.Models.Cliente", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ClienteCep")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ClienteCreditCardCvv")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ClienteCreditCardExpireDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClienteCreditCardFlag")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClienteCreditCardNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClienteCreditCardOwnerName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClienteEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ClienteImovelNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClientePassword")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });
#pragma warning restore 612, 618
        }
    }
}
